default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_DEV") { "myapp_development" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME_DEV") { "myapp" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD_DEV") { "password" } %>
  host: <%= ENV.fetch("DATABASE_HOST_DEV") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT_DEV") { 5432 } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST") { "myapp_test" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME_TEST") { "myapp" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD_TEST") { "password" } %>
  host: <%= ENV.fetch("DATABASE_HOST_TEST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT_TEST") { 5432 } %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

